name: tzens
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.4 <4.0.0'

dependencies: 
  another_carousel_pro: ^1.0.0
  cupertino_icons: ^1.0.2
  get: ^4.7.2
  firebase_core: ^4.1.0
  flutter_svg: ^2.2.0
  liquid_swipe: 3.1.0
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.1
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  water_drop_nav_bar: ^2.2.1
  dynamic_color: ^1.8.1
  animated_float_action_button: 1.0.4
  file_picker: ^10.3.2
  image_picker: ^1.0.8
  permission_handler: ^12.0.1
  firebase_storage: ^13.0.1
  liquid_pull_to_refresh: 3.0.1
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  dropdown_textfield: ^1.2.0
  firebase_messaging: ^16.0.1
  shared_preferences: ^2.5.3
  google_sign_in: ^7.1.1
  googleapis_auth: ^1.6.0
  get_storage: 2.1.1
  http: ^1.5.0
  url_launcher: ^6.0.20
  expansion_tile_list: ^2.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.1
  flutter_initicon: 3.0.1
  avatar_stack: 3.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/images/tzens.png
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
    - assets/json/
  uses-material-design: true

flutter_native_splash: 
  color: '#42a5f5'
  image: assets/images/tzens.png
  android: true
  ios: true

